import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Layout.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CRUD by nextjs</title>
        <meta name="description" content="Generated by create next app and developed by @amiryxe" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hello from Next</h1>
      <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    </div>
  )
}
